--senha userInvest - acessoInvest
--@senha sa acessoSQLServer

CREATE TABLE USUARIO (
 CPF VARCHAR(11) PRIMARY KEY,
 NOME_USUARIO VARCHAR(50) NOT NULL,
 SENHA VARCHAR(32) NOT NULL,
 CPF_USUARIO VARCHAR(11) FOREIGN KEY REFERENCES USUARIO
 );

 ALTER TABLE PATRIMONIO_RV ADD CPF_USUARIO VARCHAR(11) FOREIGN KEY REFERENCES USUARIO;
 ALTER TABLE USUARIO ALTER COLUMN SENHA VARCHAR(32);

CREATE TABLE RENDA_VARIAVEL_ORDENS_COMPRA (
 ID_Compra INT IDENTITY(1,1) PRIMARY KEY,
 Codigo_Share VARCHAR(10) NOT NULL,
 Valor MONEY NOT NULL,
 QTD SMALLINT NOT NULL,
 Tipo_Share VARCHAR(4) NOT NULL,
 DATA_COMPRA DATE NOT NULL,
 CPF_COMPRA VARCHAR(11) FOREIGN KEY REFERENCES USUARIO
 );

ALTER TABLE RENDA_VARIAVEL_ORDENS_COMPRA ADD CPF_COMPRA VARCHAR(11) FOREIGN KEY REFERENCES USUARIO;
 
CREATE TABLE RENDA_VARIAVEL_ORDENS_VENDA (
 ID_Venda INT IDENTITY(1,1) PRIMARY KEY,
 Codigo_Share VARCHAR(10) NOT NULL,
 Valor MONEY NOT NULL,
 QTD SMALLINT NOT NULL,
 Tipo_Share VARCHAR(4) NOT NULL,
 DATA_VENDA date not null
 );

 ALTER TABLE RENDA_VARIAVEL_ORDENS_VENDA ADD CPF_VENDA VARCHAR(11) FOREIGN KEY REFERENCES USUARIO;
 
 CREATE TABLE DIVIDENDO (
 ID_Pagamento INT IDENTITY(1,1) PRIMARY KEY,
 Codigo_Share_Pagador VARCHAR(10) FOREIGN KEY REFERENCES PATRIMONIO_RV,
 Valor_Share MONEY NOT NULL,
 QTD INT NOT NULL,
 Data_Pagamento date NOT NULL
 );

 ALTER TABLE DIVIDENDO ADD CPF_USUARIO VARCHAR(11) FOREIGN KEY REFERENCES USUARIO;

 CREATE TABLE RESULTADO_OPERACOES (
 ID_Resultado INT IDENTITY(1,1) PRIMARY KEY,
 Codigo_Share VARCHAR(10) FOREIGN KEY REFERENCES PATRIMONIO_RV,
 Valor_Share MONEY NOT NULL,
 QTD INT NOT NULL,
 Data_Operacao date NOT NULL,
 Resultado MONEY NOT NULL
 );

 ALTER TABLE RESULTADO_OPERACOES ADD CPF_USUARIO VARCHAR(11) FOREIGN KEY REFERENCES USUARIO;

ALTER TRIGGER Atualiza_Patrimonio
ON RENDA_VARIAVEL_ORDENS_COMPRA
AFTER INSERT AS
DECLARE
@VALOR  MONEY,
@QTD   INT,
@CODIGO VARCHAR(10),
@TIPO VARCHAR(4),
@DATA DATE,
@CPF VARCHAR(11)

SELECT @CPF = CPF_COMPRA, @DATA = DATA_COMPRA, @VALOR = VALOR, @CODIGO = CODIGO_SHARE, @QTD = QTD, @TIPO = TIPO_SHARE FROM INSERTED
BEGIN
	IF EXISTS (SELECT CODIGO_SHARE FROM PATRIMONIO_RV WHERE CODIGO_SHARE = @CODIGO AND CPF_USUARIO = @CPF)
		UPDATE PATRIMONIO_RV
		SET PRECO_MEDIO = ((SELECT QTD*PRECO_MEDIO FROM PATRIMONIO_RV WHERE CODIGO_SHARE = @CODIGO) + @QTD * @VALOR) / (@QTD + (SELECT QTD FROM PATRIMONIO_RV WHERE CODIGO_SHARE = @CODIGO)),
			QTD = @QTD + (SELECT QTD FROM PATRIMONIO_RV WHERE CODIGO_SHARE = @CODIGO)
			WHERE CODIGO_SHARE = @CODIGO
	ELSE
		INSERT INTO PATRIMONIO_RV(Codigo_Share,Preco_Medio,QTD,Tipo_Share,CPF_Usuario) VALUES (@CODIGO,@VALOR,@QTD,@TIPO,@CPF);
END


ALTER TRIGGER Atualiza_Patrimonio_Apos_Venda
ON [PLANOFINANCEIRO].[dbo].[RENDA_VARIAVEL_ORDENS_VENDA]
AFTER INSERT AS
    DECLARE
    @VALOR  MONEY,
    @QTD   INT,
	@CODIGO VARCHAR(10),
	@TIPO VARCHAR(4),
	@DATA DATE,
	@CPF VARCHAR(11)

    SELECT @CPF = CPF_VENDA, @DATA = DATA_VENDA, @VALOR = VALOR, @CODIGO = CODIGO_SHARE, @QTD = QTD, @TIPO = TIPO_SHARE FROM INSERTED
	BEGIN
		INSERT INTO RESULTADO_OPERACOES(Codigo_Share,Valor_Share,QTD,Data_Operacao,Tipo_Share,Resultado,CPF_USUARIO) 
			values (@CODIGO,@VALOR,@QTD, @DATA, @TIPO,(@QTD * @VALOR) - @QTD*(select PRECO_MEDIO from PATRIMONIO_RV where CODIGO_SHARE = @CODIGO AND CPF_USUARIO = @CPF), @CPF);
		
		UPDATE PATRIMONIO_RV
			SET QTD = ((SELECT QTD FROM PATRIMONIO_RV WHERE CODIGO_SHARE = @CODIGO) - @QTD)
			WHERE CODIGO_SHARE = @CODIGO AND CPF_USUARIO = @CPF;			
	END


